version: 0.2
phases:
  install:
    commands:
      - echo Installing Maven...
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mvn clean package -f pom.xml
  build:
    commands:
      - echo Building Docker image for backend...
      - docker build -t backend-image .
      - docker tag backend-image:latest <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push <account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend:latest
